### ISSUE TITLE
Few issues inside

### ISSUE THREAD

**Issue by SonyaDolmatova** [Pusher-Labs/asgard-exchange#72]
OK. 
#NCTN Swap: 0.583 btc for Rune (~14k)

0.583 tbtc left the wallet...
0 Rune came

No Rune, no tbtc... 

Tbtc:
tb1qws9ley9zj384kq7hqtkuu3skk0m3nel78umm8r

Tbnb:
tbnb1zzuyjf9zgvpnahfs2jdy99450jaajzugdvdady

One more thing I've noticed. Any transaction fee costs 1Rune + 0.000375 bnb.

When trying to swap tbtc for Rune , having zero Rune balance, transaction fails, because of insufficient funds. Fair! 
BUT....
When making #mctn bnb for Rune swap, having zero Rune balance, the transaction is still made..

I little bit confusing..

How could tbnb be swapped for Rune, having zero Rune balance?
![ezgif-4-1772b0bcbfb3](https://user-images.githubusercontent.com/74976410/100114448-8233ef80-2e82-11eb-91e0-b7f6b5ca2f89.gif)

**Comment by stuartkuentzel** [comment]
@SonyaDolmatova looking at your addresses in thorchain.net, it looks like swaps are going through. It may be UI related. We're working on a better flow for pending transactions. For example, it takes a while for a BTC transaction to process, but BNB transactions are very quick. So with the current flow, a BNB transaction is processed quickly, but it still takes some time for THORChain to process the transaction, then for the BTC to process. In the time between the initial transaction success and THORChain processing it, the UI displays nothing pending, which is something we are working on fixing.

Regarding having no RUNE for a transaction, I believe the THORChain network deducts that value from the pool. So the value of 1 RUNE in BTC is deducted. I just created a fresh keystore to test, with only BTC and BNB. With no RUNE, the BTC -> RUNE swap worked fine. We can update the label to be more clear.

In the future, please open separate issues, it makes them a little easier to tackle.
