### ISSUE TITLE
Some confusing price info. 

### ISSUE THREAD

**Issue by SonyaDolmatova** [Pusher-Labs/asgard-exchange#73]
Some confusing price info. Must be replaced versa
![11](https://user-images.githubusercontent.com/74976410/100115099-2cac1280-2e83-11eb-9e53-fc52eaac5655.jpg)
![22](https://user-images.githubusercontent.com/74976410/100115100-2ddd3f80-2e83-11eb-8946-ed9d791c8d0a.jpg)

**Comment by stuartkuentzel** [comment]
@SonyaDolmatova this may be because the multichain testnet pools are not properly balanced at the moment. For example, if you look at the BTC <--> RUNE swaps, the numbers are still off, but more in line with what is expected (a bunch of RUNE costs 1 BTC)
