### ISSUE TITLE
`FeeRate` !== amount of `Fee`

### ISSUE THREAD

**Issue by veado** [Pusher-Labs/asgard-exchange#76]
It's about this [line of code](https://github.com/Pusher-Labs/asgard-exchange/blob/feat/native-rune/src/app/deposit/confirm-deposit-modal/confirm-deposit-modal.component.ts#L232) in `confirm-deposit-modal.component.ts ` (branch [feat/native-rune](https://github.com/Pusher-Labs/asgard-exchange/blob/feat/native-rune)). Check your implementation of `bitcoinClient.transfer` at other places, where you have done it right ;)

**Comment by stuartkuentzel** [comment]
thanks for the catch @veado https://github.com/Pusher-Labs/asgard-exchange/commit/acec25759ba5e46e2b97707f4ae26ff0c5490cb2 should close this
