### ISSUE TITLE
Sending txn to Binance Chain

### ISSUE THREAD

**Issue by sahilpant** [Pusher-Labs/asgard-exchange#77]
Don't know why but when I tried to send the txn to binance chain using the @xchainjs/xchain-binance and asset as BNB it gave me error but after removing the asset flag in the transfer function txn went through I think there is no need for sending the asset in the transfer function.

https://github.com/sahilpant/asgard-exchange/blob/master/src/app/swap/confirm-swap-modal/confirm-swap-modal.component.ts#L162

**Comment by stuartkuentzel** [comment]
Hey @sahilpant, this issue should already be addressed in the upcoming `feat/native-rune` branch.
